eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
      
management:
   security:
      enabled: false
      
management:
    endpoints:
       web:
           exposure:
               include: *

com:
   ReturnStatement: "Logged In"
